// 人教版九年级英语全一册高频考单词数据
const wordsData = [
    // Unit 1: How can we become good learners?
    {id: 1, english: "aloud", phonetic: "/əˈlaʊd/", chinese: "大声地；出声地", unit: 1, category: "高频词", difficulty: "easy"},
    {id: 2, english: "pronunciation", phonetic: "/prəˌnʌnsiˈeɪʃn/", chinese: "发音；读音", unit: 1, category: "高频词", difficulty: "medium"},
    {id: 3, english: "sentence", phonetic: "/ˈsentəns/", chinese: "句子", unit: 1, category: "基础词", difficulty: "easy"},
    {id: 4, english: "patient", phonetic: "/ˈpeɪʃnt/", chinese: "有耐心的；病人", unit: 1, category: "高频词", difficulty: "medium"},
    {id: 5, english: "discover", phonetic: "/dɪˈskʌvər/", chinese: "发现；发觉", unit: 1, category: "高频词", difficulty: "medium"},
    {id: 6, english: "secret", phonetic: "/ˈsiːkrət/", chinese: "秘密；秘诀", unit: 1, category: "基础词", difficulty: "easy"},
    {id: 7, english: "grammar", phonetic: "/ˈɡræmər/", chinese: "语法", unit: 1, category: "高频词", difficulty: "medium"},
    {id: 8, english: "repeat", phonetic: "/rɪˈpiːt/", chinese: "重复；重做", unit: 1, category: "基础词", difficulty: "easy"},
    {id: 9, english: "note", phonetic: "/nəʊt/", chinese: "笔记；记录", unit: 1, category: "基础词", difficulty: "easy"},
    {id: 10, english: "pal", phonetic: "/pæl/", chinese: "朋友；伙伴", unit: 1, category: "口语词", difficulty: "easy"},
    {id: 11, english: "physics", phonetic: "/ˈfɪzɪks/", chinese: "物理；物理学", unit: 1, category: "学科词", difficulty: "medium"},
    {id: 12, english: "chemistry", phonetic: "/ˈkemɪstri/", chinese: "化学", unit: 1, category: "学科词", difficulty: "medium"},
    {id: 13, english: "memorize", phonetic: "/ˈmeməraɪz/", chinese: "记住；记忆", unit: 1, category: "高频词", difficulty: "medium"},
    {id: 14, english: "pattern", phonetic: "/ˈpætn/", chinese: "模式；图案", unit: 1, category: "高频词", difficulty: "medium"},
    {id: 15, english: "pronounce", phonetic: "/prəˈnaʊns/", chinese: "发音", unit: 1, category: "高频词", difficulty: "medium"},

    // Unit 2: I think that mooncakes are delicious!
    {id: 16, english: "mooncake", phonetic: "/ˈmuːnkeɪk/", chinese: "月饼", unit: 2, category: "节日词", difficulty: "easy"},
    {id: 17, english: "lantern", phonetic: "/ˈlæntən/", chinese: "灯笼", unit: 2, category: "节日词", difficulty: "easy"},
    {id: 18, english: "festival", phonetic: "/ˈfestɪvl/", chinese: "节日", unit: 2, category: "高频词", difficulty: "easy"},
    {id: 19, english: "traditional", phonetic: "/trəˈdɪʃənl/", chinese: "传统的", unit: 2, category: "高频词", difficulty: "medium"},
    {id: 20, english: "celebrate", phonetic: "/ˈselɪbreɪt/", chinese: "庆祝", unit: 2, category: "高频词", difficulty: "medium"},
    {id: 21, english: "relative", phonetic: "/ˈrelətɪv/", chinese: "亲属；亲戚", unit: 2, category: "基础词", difficulty: "easy"},
    {id: 22, english: "gather", phonetic: "/ˈɡæðər/", chinese: "聚集；集合", unit: 2, category: "高频词", difficulty: "medium"},
    {id: 23, english: "harvest", phonetic: "/ˈhɑːrvɪst/", chinese: "收获；收成", unit: 2, category: "高频词", difficulty: "medium"},
    {id: 24, english: "admire", phonetic: "/ədˈmaɪər/", chinese: "欣赏；仰慕", unit: 2, category: "高频词", difficulty: "medium"},
    {id: 25, english: "ghost", phonetic: "/ɡəʊst/", chinese: "鬼；幽灵", unit: 2, category: "节日词", difficulty: "easy"},
    {id: 26, english: "trick", phonetic: "/trɪk/", chinese: "诡计；恶作剧", unit: 2, category: "节日词", difficulty: "easy"},
    {id: 27, english: "treat", phonetic: "/triːt/", chinese: "款待；招待", unit: 2, category: "节日词", difficulty: "easy"},
    {id: 28, english: "costume", phonetic: "/ˈkɒstjuːm/", chinese: "服装；装束", unit: 2, category: "节日词", difficulty: "medium"},
    {id: 29, english: "candy", phonetic: "/ˈkændi/", chinese: "糖果", unit: 2, category: "基础词", difficulty: "easy"},
    {id: 30, english: "Christmas", phonetic: "/ˈkrɪsməs/", chinese: "圣诞节", unit: 2, category: "节日词", difficulty: "easy"},

    // Unit 3: I'm more outgoing than my sister.
    {id: 31, english: "outgoing", phonetic: "/ˈaʊtɡəʊɪŋ/", chinese: "外向的；友好的", unit: 3, category: "性格词", difficulty: "medium"},
    {id: 32, english: "quiet", phonetic: "/ˈkwaɪət/", chinese: "安静的；文静的", unit: 3, category: "性格词", difficulty: "easy"},
    {id: 33, english: "shy", phonetic: "/ʃaɪ/", chinese: "害羞的；腼腆的", unit: 3, category: "性格词", difficulty: "easy"},
    {id: 34, english: "friendly", phonetic: "/ˈfrendli/", chinese: "友好的", unit: 3, category: "性格词", difficulty: "easy"},
    {id: 35, english: "hardworking", phonetic: "/ˌhɑːrdˈwɜːrkɪŋ/", chinese: "勤奋的", unit: 3, category: "性格词", difficulty: "medium"},
    {id: 36, english: "competition", phonetic: "/ˌkɑːmpəˈtɪʃn/", chinese: "比赛；竞赛", unit: 3, category: "高频词", difficulty: "medium"},
    {id: 37, english: "talented", phonetic: "/ˈtæləntɪd/", chinese: "有天赋的", unit: 3, category: "高频词", difficulty: "medium"},
    {id: 38, english: "truly", phonetic: "/ˈtruːli/", chinese: "真正；确实", unit: 3, category: "副词", difficulty: "medium"},
    {id: 39, english: "care", phonetic: "/ker/", chinese: "关心；在意", unit: 3, category: "基础词", difficulty: "easy"},
    {id: 40, english: "laugh", phonetic: "/læf/", chinese: "笑；发笑", unit: 3, category: "基础词", difficulty: "easy"},
    {id: 41, english: "share", phonetic: "/ʃer/", chinese: "分享；共享", unit: 3, category: "基础词", difficulty: "easy"},
    {id: 42, english: "similar", phonetic: "/ˈsɪmələr/", chinese: "相似的", unit: 3, category: "高频词", difficulty: "medium"},
    {id: 43, english: "primary", phonetic: "/ˈpraɪmeri/", chinese: "初级的；小学的", unit: 3, category: "高频词", difficulty: "medium"},
    {id: 44, english: "information", phonetic: "/ˌɪnfərˈmeɪʃn/", chinese: "信息；资料", unit: 3, category: "高频词", difficulty: "easy"},
    {id: 45, english: "volunteer", phonetic: "/ˌvɑːlənˈtɪr/", chinese: "志愿者", unit: 3, category: "高频词", difficulty: "medium"},

    // Unit 4: What's the best movie theater?
    {id: 46, english: "theater", phonetic: "/ˈθiːətər/", chinese: "剧院；电影院", unit: 4, category: "场所词", difficulty: "easy"},
    {id: 47, english: "comfortable", phonetic: "/ˈkʌmftəbl/", chinese: "舒适的", unit: 4, category: "高频词", difficulty: "medium"},
    {id: 48, english: "seat", phonetic: "/siːt/", chinese: "座位", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 49, english: "screen", phonetic: "/skriːn/", chinese: "屏幕", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 50, english: "close", phonetic: "/kloʊs/", chinese: "接近的", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 51, english: "cheap", phonetic: "/tʃiːp/", chinese: "便宜的", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 52, english: "service", phonetic: "/ˈsɜːrvɪs/", chinese: "服务", unit: 4, category: "高频词", difficulty: "medium"},
    {id: 53, english: "creative", phonetic: "/kriˈeɪtɪv/", chinese: "创造性的", unit: 4, category: "高频词", difficulty: "medium"},
    {id: 54, english: "talent", phonetic: "/ˈtælənt/", chinese: "天赋；才能", unit: 4, category: "高频词", difficulty: "medium"},
    {id: 55, english: "performer", phonetic: "/pərˈfɔːrmər/", chinese: "表演者", unit: 4, category: "高频词", difficulty: "medium"},
    {id: 56, english: "role", phonetic: "/roʊl/", chinese: "角色", unit: 4, category: "高频词", difficulty: "easy"},
    {id: 57, english: "prize", phonetic: "/praɪz/", chinese: "奖品；奖金", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 58, english: "winner", phonetic: "/ˈwɪnər/", chinese: "获胜者", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 59, english: "example", phonetic: "/ɪɡˈzæmpl/", chinese: "例子；榜样", unit: 4, category: "基础词", difficulty: "easy"},
    {id: 60, english: "poor", phonetic: "/pʊr/", chinese: "贫穷的；可怜的", unit: 4, category: "基础词", difficulty: "easy"},

    // Unit 5: What are the shirts made of?
    {id: 61, english: "material", phonetic: "/məˈtɪriəl/", chinese: "材料；原料", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 62, english: "cotton", phonetic: "/ˈkɑːtn/", chinese: "棉花；棉的", unit: 5, category: "材料词", difficulty: "easy"},
    {id: 63, english: "silk", phonetic: "/sɪlk/", chinese: "丝绸；丝的", unit: 5, category: "材料词", difficulty: "easy"},
    {id: 64, english: "wool", phonetic: "/wʊl/", chinese: "羊毛；毛料的", unit: 5, category: "材料词", difficulty: "easy"},
    {id: 65, english: "leather", phonetic: "/ˈleðər/", chinese: "皮革；皮革制的", unit: 5, category: "材料词", difficulty: "medium"},
    {id: 66, english: "produce", phonetic: "/prəˈduːs/", chinese: "生产；制造", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 67, english: "product", phonetic: "/ˈprɑːdʌkt/", chinese: "产品；制品", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 68, english: "factory", phonetic: "/ˈfæktri/", chinese: "工厂", unit: 5, category: "高频词", difficulty: "easy"},
    {id: 69, english: "machine", phonetic: "/məˈʃiːn/", chinese: "机器", unit: 5, category: "高频词", difficulty: "easy"},
    {id: 70, english: "invent", phonetic: "/ɪnˈvent/", chinese: "发明；创造", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 71, english: "invention", phonetic: "/ɪnˈvenʃn/", chinese: "发明；创造", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 72, english: "paper", phonetic: "/ˈpeɪpər/", chinese: "纸；纸张", unit: 5, category: "基础词", difficulty: "easy"},
    {id: 73, english: "printing", phonetic: "/ˈprɪntɪŋ/", chinese: "印刷", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 74, english: "business", phonetic: "/ˈbɪznəs/", chinese: "商业；生意", unit: 5, category: "高频词", difficulty: "medium"},
    {id: 75, english: "industry", phonetic: "/ˈɪndəstri/", chinese: "工业；产业", unit: 5, category: "高频词", difficulty: "medium"},

    // Unit 6: When was it invented?
    {id: 76, english: "inventor", phonetic: "/ɪnˈventər/", chinese: "发明家", unit: 6, category: "高频词", difficulty: "medium"},
    {id: 77, english: "telephone", phonetic: "/ˈtelɪfoʊn/", chinese: "电话", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 78, english: "radio", phonetic: "/ˈreɪdioʊ/", chinese: "收音机；无线电", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 79, english: "television", phonetic: "/ˈtelɪvɪʒn/", chinese: "电视", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 80, english: "computer", phonetic: "/kəmˈpjuːtər/", chinese: "电脑；计算机", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 81, english: "Internet", phonetic: "/ˈɪntərnet/", chinese: "互联网", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 82, english: "website", phonetic: "/ˈwebsaɪt/", chinese: "网站", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 83, english: "digital", phonetic: "/ˈdɪdʒɪtl/", chinese: "数字的；数码的", unit: 6, category: "科技词", difficulty: "medium"},
    {id: 84, english: "technology", phonetic: "/tekˈnɑːlədʒi/", chinese: "技术；科技", unit: 6, category: "高频词", difficulty: "medium"},
    {id: 85, english: "communication", phonetic: "/kəˌmjuːnɪˈkeɪʃn/", chinese: "交流；沟通", unit: 6, category: "高频词", difficulty: "medium"},
    {id: 86, english: "message", phonetic: "/ˈmesɪdʒ/", chinese: "信息；消息", unit: 6, category: "基础词", difficulty: "easy"},
    {id: 87, english: "e-mail", phonetic: "/ˈiː meɪl/", chinese: "电子邮件", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 88, english: "smartphone", phonetic: "/ˈsmɑːrtfoʊn/", chinese: "智能手机", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 89, english: "keyboard", phonetic: "/ˈkiːbɔːrd/", chinese: "键盘", unit: 6, category: "科技词", difficulty: "easy"},
    {id: 90, english: "screen", phonetic: "/skriːn/", chinese: "屏幕", unit: 6, category: "科技词", difficulty: "easy"},

    // Unit 7: Teenagers should be allowed to choose their own clothes.
    {id: 91, english: "allow", phonetic: "/əˈlaʊ/", chinese: "允许；准许", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 92, english: "license", phonetic: "/ˈlaɪsns/", chinese: "执照；许可证", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 93, english: "safety", phonetic: "/ˈseɪfti/", chinese: "安全；安全性", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 94, english: "smoke", phonetic: "/smoʊk/", chinese: "吸烟；烟", unit: 7, category: "基础词", difficulty: "easy"},
    {id: 95, english: "pierce", phonetic: "/pɪrs/", chinese: "刺穿；刺破", unit: 7, category: "动词", difficulty: "hard"},
    {id: 96, english: "earring", phonetic: "/ˈɪrɪŋ/", chinese: "耳环", unit: 7, category: "名词", difficulty: "easy"},
    {id: 97, english: "flash", phonetic: "/flæʃ/", chinese: "闪光灯；闪光", unit: 7, category: "名词", difficulty: "medium"},
    {id: 98, english: "teenager", phonetic: "/ˈtiːneɪdʒər/", chinese: "青少年", unit: 7, category: "高频词", difficulty: "easy"},
    {id: 99, english: "rule", phonetic: "/ruːl/", chinese: "规则；规定", unit: 7, category: "基础词", difficulty: "easy"},
    {id: 100, english: "strict", phonetic: "/strɪkt/", chinese: "严格的；严厉的", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 101, english: "parent", phonetic: "/ˈpeərənt/", chinese: "父（母）亲", unit: 7, category: "基础词", difficulty: "easy"},
    {id: 102, english: "choice", phonetic: "/tʃɔɪs/", chinese: "选择；决定", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 103, english: "decision", phonetic: "/dɪˈsɪʒn/", chinese: "决定；抉择", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 104, english: "opinion", phonetic: "/əˈpɪnjən/", chinese: "意见；想法", unit: 7, category: "高频词", difficulty: "medium"},
    {id: 105, english: "agree", phonetic: "/əˈɡriː/", chinese: "同意；赞成", unit: 7, category: "基础词", difficulty: "easy"},

    // Unit 8: It must belong to Carla.
    {id: 106, english: "belong", phonetic: "/bɪˈlɔːŋ/", chinese: "属于；归属", unit: 8, category: "高频词", difficulty: "medium"},
    {id: 107, english: "wallet", phonetic: "/ˈwɑːlɪt/", chinese: "钱包", unit: 8, category: "名词", difficulty: "easy"},
    {id: 108, english: "valuable", phonetic: "/ˈvæljuəbl/", chinese: "贵重的；有价值的", unit: 8, category: "形容词", difficulty: "medium"},
    {id: 109, english: "pink", phonetic: "/pɪŋk/", chinese: "粉红色的", unit: 8, category: "颜色词", difficulty: "easy"},
    {id: 110, english: "toy", phonetic: "/tɔɪ/", chinese: "玩具", unit: 8, category: "名词", difficulty: "easy"},
    {id: 111, english: "magazine", phonetic: "/ˌmæɡəˈziːn/", chinese: "杂志；期刊", unit: 8, category: "名词", difficulty: "easy"},
    {id: 112, english: "novel", phonetic: "/ˈnɑːvl/", chinese: "小说", unit: 8, category: "名词", difficulty: "easy"},
    {id: 113, english: "author", phonetic: "/ˈɔːθər/", chinese: "作者；作家", unit: 8, category: "名词", difficulty: "medium"},
    {id: 114, english: "picnic", phonetic: "/ˈpɪknɪk/", chinese: "野餐", unit: 8, category: "名词", difficulty: "easy"},
    {id: 115, english: "possibly", phonetic: "/ˈpɑːsəbli/", chinese: "可能；也许", unit: 8, category: "副词", difficulty: "medium"},
    {id: 116, english: "drop", phonetic: "/drɑːp/", chinese: "掉下；落下", unit: 8, category: "动词", difficulty: "easy"},
    {id: 117, english: "clue", phonetic: "/kluː/", chinese: "线索；提示", unit: 8, category: "名词", difficulty: "medium"},
    {id: 118, english: "mystery", phonetic: "/ˈmɪstri/", chinese: "谜；神秘事物", unit: 8, category: "名词", difficulty: "medium"},
    {id: 119, english: "owner", phonetic: "/ˈoʊnər/", chinese: "所有者；主人", unit: 8, category: "名词", difficulty: "easy"},
    {id: 120, english: "happening", phonetic: "/ˈhæpənɪŋ/", chinese: "事件；发生的事情", unit: 8, category: "名词", difficulty: "medium"},

    // Unit 9: I like music that I can dance to.
    {id: 121, english: "music", phonetic: "/ˈmjuːzɪk/", chinese: "音乐；乐曲", unit: 9, category: "基础词", difficulty: "easy"},
    {id: 122, english: "dance", phonetic: "/dæns/", chinese: "跳舞；舞蹈", unit: 9, category: "基础词", difficulty: "easy"},
    {id: 123, english: "musician", phonetic: "/mjuˈzɪʃn/", chinese: "音乐家；乐师", unit: 9, category: "名词", difficulty: "medium"},
    {id: 124, english: "singer", phonetic: "/ˈsɪŋər/", chinese: "歌手；歌唱家", unit: 9, category: "名词", difficulty: "easy"},
    {id: 125, english: "band", phonetic: "/bænd/", chinese: "乐队；带子", unit: 9, category: "名词", difficulty: "easy"},
    {id: 126, english: "concert", phonetic: "/ˈkɑːnsərt/", chinese: "音乐会；演奏会", unit: 9, category: "名词", difficulty: "easy"},
    {id: 127, english: "album", phonetic: "/ˈælbəm/", chinese: "专辑；唱片", unit: 9, category: "名词", difficulty: "medium"},
    {id: 128, english: "song", phonetic: "/sɔːŋ/", chinese: "歌曲；歌唱", unit: 9, category: "基础词", difficulty: "easy"},
    {id: 129, english: "lyrics", phonetic: "/ˈlɪrɪks/", chinese: "歌词", unit: 9, category: "名词", difficulty: "medium"},
    {id: 130, english: "melody", phonetic: "/ˈmelədi/", chinese: "旋律；曲调", unit: 9, category: "名词", difficulty: "medium"},
    {id: 131, english: "classical", phonetic: "/ˈklæsɪkl/", chinese: "古典的；经典的", unit: 9, category: "形容词", difficulty: "medium"},
    {id: 132, english: "country", phonetic: "/ˈkʌntri/", chinese: "乡村音乐；国家", unit: 9, country: "多义词", difficulty: "easy"},
    {id: 133, english: "jazz", phonetic: "/dʒæz/", chinese: "爵士乐", unit: 9, category: "音乐词", difficulty: "medium"},
    {id: 134, english: "rock", phonetic: "/rɑːk/", chinese: "摇滚乐；岩石", unit: 9, category: "多义词", difficulty: "easy"},
    {id: 135, english: "pop", phonetic: "/pɑːp/", chinese: "流行乐；流行的", unit: 9, category: "音乐词", difficulty: "easy"},

    // Unit 10: You're supposed to shake hands.
    {id: 136, english: "supposed", phonetic: "/səˈpoʊzd/", chinese: "应该；被期望", unit: 10, category: "高频词", difficulty: "medium"},
    {id: 137, english: "shake", phonetic: "/ʃeɪk/", chinese: "摇动；握手", unit: 10, category: "动词", difficulty: "easy"},
    {id: 138, english: "hands", phonetic: "/hændz/", chinese: "手（复数）", unit: 10, category: "基础词", difficulty: "easy"},
    {id: 139, english: "custom", phonetic: "/ˈkʌstəm/", chinese: "风俗；习俗", unit: 10, category: "高频词", difficulty: "medium"},
    {id: 140, english: "culture", phonetic: "/ˈkʌltʃər/", chinese: "文化；文明", unit: 10, category: "高频词", difficulty: "medium"},
    {id: 141, english: "manner", phonetic: "/ˈmænər/", chinese: "方式；举止", unit: 10, category: "高频词", difficulty: "medium"},
    {id: 142, english: "greet", phonetic: "/ɡriːt/", chinese: "问候；打招呼", unit: 10, category: "动词", difficulty: "easy"},
    {id: 143, english: "kiss", phonetic: "/kɪs/", chinese: "吻；亲吻", unit: 10, category: "动词", difficulty: "easy"},
    {id: 144, english: "bow", phonetic: "/baʊ/", chinese: "鞠躬；弯腰", unit: 10, category: "动词", difficulty: "easy"},
    {id: 145, english: "polite", phonetic: "/pəˈlaɪt/", chinese: "有礼貌的", unit: 10, category: "形容词", difficulty: "medium"},
    {id: 146, english: "impolite", phonetic: "/ˌɪmpəˈlaɪt/", chinese: "不礼貌的", unit: 10, category: "形容词", difficulty: "medium"},
    {id: 147, english: "behavior", phonetic: "/bɪˈheɪvjər/", chinese: "行为；举止", unit: 10, category: "名词", difficulty: "medium"},
    {id: 148, english: "gesture", phonetic: "/ˈdʒestʃər/", chinese: "姿势；手势", unit: 10, category: "名词", difficulty: "medium"},
    {id: 149, english: "table", phonetic: "/ˈteɪbl/", chinese: "桌子；表格", unit: 10, category: "基础词", difficulty: "easy"},
    {id: 150, english: "manners", phonetic: "/ˈmænərz/", chinese: "礼貌；礼仪", unit: 10, category: "名词", difficulty: "medium"},

    // Unit 11: Sad movies make me cry.
    {id: 151, english: "sad", phonetic: "/sæd/", chinese: "悲伤的；难过的", unit: 11, category: "情感词", difficulty: "easy"},
    {id: 152, english: "movie", phonetic: "/ˈmuːvi/", chinese: "电影", unit: 11, category: "基础词", difficulty: "easy"},
    {id: 153, english: "cry", phonetic: "/kraɪ/", chinese: "哭；哭泣", unit: 11, category: "动词", difficulty: "easy"},
    {id: 154, english: "happy", phonetic: "/ˈhæpi/", chinese: "快乐的；幸福的", unit: 11, category: "情感词", difficulty: "easy"},
    {id: 155, english: "excited", phonetic: "/ɪkˈsaɪtɪd/", chinese: "激动的；兴奋的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 156, english: "bored", phonetic: "/bɔːrd/", chinese: "无聊的；厌倦的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 157, english: "relaxed", phonetic: "/rɪˈlækst/", chinese: "放松的；轻松的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 158, english: "nervous", phonetic: "/ˈnɜːrvəs/", chinese: "紧张的；焦虑的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 159, english: "proud", phonetic: "/praʊd/", chinese: "自豪的；骄傲的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 160, english: "disappointed", phonetic: "/ˌdɪsəˈpɔɪntɪd/", chinese: "失望的；沮丧的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 161, english: "frightened", phonetic: "/ˈfraɪtnd/", chinese: "受惊的；害怕的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 162, english: "embarrassed", phonetic: "/ɪmˈbærəst/", chinese: "尴尬的；窘迫的", unit: 11, category: "情感词", difficulty: "medium"},
    {id: 163, english: "feeling", phonetic: "/ˈfiːlɪŋ/", chinese: "感觉；情感", unit: 11, category: "名词", difficulty: "easy"},
    {id: 164, english: "emotion", phonetic: "/ɪˈmoʊʃn/", chinese: "情感；情绪", unit: 11, category: "名词", difficulty: "medium"},
    {id: 165, english: "experience", phonetic: "/ɪkˈspɪriəns/", chinese: "经历；经验", unit: 11, category: "名词", difficulty: "medium"},

    // Unit 12: Life is full of the unexpected.
    {id: 166, english: "life", phonetic: "/laɪf/", chinese: "生活；生命", unit: 12, category: "基础词", difficulty: "easy"},
    {id: 167, english: "full", phonetic: "/fʊl/", chinese: "充满的；完全的", unit: 12, category: "基础词", difficulty: "easy"},
    {id: 168, english: "unexpected", phonetic: "/ˌʌnɪkˈspektɪd/", chinese: "出乎意料的", unit: 12, category: "形容词", difficulty: "hard"},
    {id: 169, english: "surprise", phonetic: "/sərˈpraɪz/", chinese: "惊喜；惊讶", unit: 12, category: "名词", difficulty: "easy"},
    {id: 170, english: "suddenly", phonetic: "/ˈsʌdənli/", chinese: "突然地", unit: 12, category: "副词", difficulty: "medium"},
    {id: 171, english: "accident", phonetic: "/ˈæksɪdənt/", chinese: "事故；意外", unit: 12, category: "名词", difficulty: "medium"},
    {id: 172, english: "incident", phonetic: "/ˈɪnsɪdənt/", chinese: "事件；事变", unit: 12, category: "名词", difficulty: "medium"},
    {id: 173, english: "strange", phonetic: "/streɪndʒ/", chinese: "奇怪的；陌生的", unit: 12, category: "形容词", difficulty: "medium"},
    {id: 174, english: "weird", phonetic: "/wɪrd/", chinese: "怪异的；不可思议的", unit: 12, category: "形容词", difficulty: "medium"},
    {id: 175, english: "miracle", phonetic: "/ˈmɪrəkl/", chinese: "奇迹；奇事", unit: 12, category: "名词", difficulty: "medium"},
    {id: 176, english: "luck", phonetic: "/lʌk/", chinese: "运气；幸运", unit: 12, category: "名词", difficulty: "easy"},
    {id: 177, english: "lucky", phonetic: "/ˈlʌki/", chinese: "幸运的", unit: 12, category: "形容词", difficulty: "easy"},
    {id: 178, english: "unlucky", phonetic: "/ʌnˈlʌki/", chinese: "不幸的", unit: 12, category: "形容词", difficulty: "easy"},
    {id: 179, english: "chance", phonetic: "/tʃæns/", chinese: "机会；可能性", unit: 12, category: "名词", difficulty: "medium"},
    {id: 180, english: "opportunity", phonetic: "/ˌɑːpərˈtuːnəti/", chinese: "机会；时机", unit: 12, category: "名词", difficulty: "medium"},

    // Unit 13: We're trying to save the earth!
    {id: 181, english: "try", phonetic: "/traɪ/", chinese: "尝试；努力", unit: 13, category: "基础词", difficulty: "easy"},
    {id: 182, english: "save", phonetic: "/seɪv/", chinese: "拯救；节约", unit: 13, category: "基础词", difficulty: "easy"},
    {id: 183, english: "earth", phonetic: "/ɜːrθ/", chinese: "地球；陆地", unit: 13, category: "基础词", difficulty: "easy"},
    {id: 184, english: "environment", phonetic: "/ɪnˈvaɪrənmənt/", chinese: "环境；自然环境", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 185, english: "pollution", phonetic: "/pəˈluːʃn/", chinese: "污染；污染物", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 186, english: "protect", phonetic: "/prəˈtekt/", chinese: "保护；防护", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 187, english: "recycle", phonetic: "/ˌriːˈsaɪkl/", chinese: "回收；再利用", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 188, english: "waste", phonetic: "/weɪst/", chinese: "浪费；废物", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 189, english: "energy", phonetic: "/ˈenərdʒi/", chinese: "能源；能量", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 190, english: "resource", phonetic: "/ˈriːsɔːrs/", chinese: "资源；资料", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 191, english: "nature", phonetic: "/ˈneɪtʃər/", chinese: "自然；自然界", unit: 13, category: "高频词", difficulty: "medium"},
    {id: 192, english: "natural", phonetic: "/ˈnætʃərəl/", chinese: "自然的；天然的", unit: 13, category: "形容词", difficulty: "medium"},
    {id: 193, english: "plastic", phonetic: "/ˈplæstɪk/", chinese: "塑料的；塑料", unit: 13, category: "材料词", difficulty: "easy"},
    {id: 194, english: "garbage", phonetic: "/ˈɡɑːrbɪdʒ/", chinese: "垃圾；废物", unit: 13, category: "名词", difficulty: "easy"},
    {id: 195, english: "litter", phonetic: "/ˈlɪtər/", chinese: "乱扔垃圾；垃圾", unit: 13, category: "动词", difficulty: "medium"},

    // Unit 14: I remember meeting all of you in Grade 7.
    {id: 196, english: "remember", phonetic: "/rɪˈmembər/", chinese: "记得；记住", unit: 14, category: "基础词", difficulty: "easy"},
    {id: 197, english: "meet", phonetic: "/miːt/", chinese: "遇见；见面", unit: 14, category: "基础词", difficulty: "easy"},
    {id: 198, english: "grade", phonetic: "/ɡreɪd/", chinese: "年级；等级", unit: 14, category: "基础词", difficulty: "easy"},
    {id: 199, english: "junior", phonetic: "/ˈdʒuːniər/", chinese: "初级的；年少的", unit: 14, category: "形容词", difficulty: "medium"},
    {id: 200, english: "senior", phonetic: "/ˈsiːniər/", chinese: "高级的；年长的", unit: 14, category: "形容词", difficulty: "medium"},
    {id: 201, english: "memory", phonetic: "/ˈmeməri/", chinese: "记忆；回忆", unit: 14, category: "名词", difficulty: "medium"},
    {id: 202, english: "friendship", phonetic: "/ˈfrendʃɪp/", chinese: "友谊；友情", unit: 14, category: "名词", difficulty: "easy"},
    {id: 203, english: "classmate", phonetic: "/ˈklæsmeɪt/", chinese: "同班同学", unit: 14, category: "名词", difficulty: "easy"},
    {id: 204, english: "teacher", phonetic: "/ˈtiːtʃər/", chinese: "老师；教师", unit: 14, category: "基础词", difficulty: "easy"},
    {id: 205, english: "school", phonetic: "/skuːl/", chinese: "学校；上学", unit: 14, category: "基础词", difficulty: "easy"},
    {id: 206, english: "graduate", phonetic: "/ˈɡrædʒueɪt/", chinese: "毕业；毕业生", unit: 14, category: "动词", difficulty: "medium"},
    {id: 207, english: "future", phonetic: "/ˈfjuːtʃər/", chinese: "将来；未来", unit: 14, category: "名词", difficulty: "easy"},
    {id: 208, english: "dream", phonetic: "/driːm/", chinese: "梦想；做梦", unit: 14, category: "名词", difficulty: "easy"},
    {id: 209, english: "hope", phonetic: "/hoʊp/", chinese: "希望；期望", unit: 14, category: "动词", difficulty: "easy"},
    {id: 210, english: "success", phonetic: "/səkˈses/", chinese: "成功；成就", unit: 14, category: "名词", difficulty: "medium"},

    // 额外的高频考词
    {id: 211, english: "achieve", phonetic: "/əˈtʃiːv/", chinese: "达到；实现", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 212, english: "advantage", phonetic: "/ədˈvæntɪdʒ/", chinese: "优势；好处", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 213, english: "ancient", phonetic: "/ˈeɪnʃənt/", chinese: "古代的；古老的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 214, english: "appear", phonetic: "/əˈpɪr/", chinese: "出现；显得", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 215, english: "apply", phonetic: "/əˈplaɪ/", chinese: "申请；应用", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 216, english: "appoint", phonetic: "/əˈpɔɪnt/", chinese: "任命；指定", unit: 0, category: "高频词", difficulty: "hard"},
    {id: 217, english: "approach", phonetic: "/əˈproʊtʃ/", chinese: "接近；方法", unit: 0, category: "高频词", difficulty: "hard"},
    {id: 218, english: "argue", phonetic: "/ˈɑːrɡjuː/", chinese: "争论；辩论", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 219, english: "arrive", phonetic: "/əˈraɪv/", chinese: "到达；抵达", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 220, english: "attack", phonetic: "/əˈtæk/", chinese: "攻击；抨击", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 221, english: "attend", phonetic: "/əˈtend/", chinese: "参加；出席", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 222, english: "avoid", phonetic: "/əˈvɔɪd/", chinese: "避免；回避", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 223, english: "basic", phonetic: "/ˈbeɪsɪk/", chinese: "基本的；基础的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 224, english: "believe", phonetic: "/bɪˈliːv/", chinese: "相信；认为", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 225, english: "borrow", phonetic: "/ˈbɑːroʊ/", chinese: "借入；借用", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 226, english: "bother", phonetic: "/ˈbɑːðər/", chinese: "打扰；烦扰", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 227, english: "bright", phonetic: "/braɪt/", chinese: "明亮的；聪明的", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 228, english: "business", phonetic: "/ˈbɪznəs/", chinese: "商业；生意", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 229, english: "calm", phonetic: "/kɑːm/", chinese: "平静的；冷静的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 230, english: "careful", phonetic: "/ˈkerfl/", chinese: "小心的；仔细的", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 231, english: "certain", phonetic: "/ˈsɜːrtn/", chinese: "确定的；无疑的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 232, english: "challenge", phonetic: "/ˈtʃælɪndʒ/", chinese: "挑战；质疑", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 233, english: "chance", phonetic: "/tʃæns/", chinese: "机会；可能性", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 234, english: "change", phonetic: "/tʃeɪndʒ/", chinese: "改变；变化", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 235, english: "character", phonetic: "/ˈkærəktər/", chinese: "性格；角色；文字", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 236, english: "cheap", phonetic: "/tʃiːp/", chinese: "便宜的", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 237, english: "choose", phonetic: "/tʃuːz/", chinese: "选择；挑选", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 238, english: "clear", phonetic: "/klɪr/", chinese: "清楚的；明确的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 239, english: "climb", phonetic: "/klaɪm/", chinese: "爬；攀登", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 240, english: "compare", phonetic: "/kəmˈper/", chinese: "比较；对比", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 241, english: "complain", phonetic: "/kəmˈpleɪn/", chinese: "抱怨；诉苦", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 242, english: "complete", phonetic: "/kəmˈpliːt/", chinese: "完成；完全的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 243, english: "consider", phonetic: "/kənˈsɪdər/", chinese: "考虑；认为", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 244, english: "continue", phonetic: "/kənˈtɪnjuː/", chinese: "继续；延续", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 245, english: "correct", phonetic: "/kəˈrekt/", chinese: "正确的；改正", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 246, english: "cost", phonetic: "/kɔːst/", chinese: "花费；成本", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 247, english: "create", phonetic: "/kriˈeɪt/", chinese: "创造；创建", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 248, english: "culture", phonetic: "/ˈkʌltʃər/", chinese: "文化；文明", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 249, english: "curious", phonetic: "/ˈkjʊriəs/", chinese: "好奇的；奇异的", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 250, english: "daily", phonetic: "/ˈdeɪli/", chinese: "每日的；日常的", unit: 0, category: "高频词", difficulty: "medium"},

    // 更多高频词汇
    {id: 251, english: "damage", phonetic: "/ˈdæmɪdʒ/", chinese: "损害；破坏", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 252, english: "danger", phonetic: "/ˈdeɪndʒər/", chinese: "危险；风险", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 253, english: "dangerous", phonetic: "/ˈdeɪndʒərəs/", chinese: "危险的", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 254, english: "decide", phonetic: "/dɪˈsaɪd/", chinese: "决定；下决心", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 255, english: "decision", phonetic: "/dɪˈsɪʒn/", chinese: "决定；抉择", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 256, english: "describe", phonetic: "/dɪˈskraɪb/", chinese: "描述；形容", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 257, english: "develop", phonetic: "/dɪˈveləp/", chinese: "发展；开发", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 258, english: "development", phonetic: "/dɪˈveləpmənt/", chinese: "发展；开发", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 259, english: "difference", phonetic: "/ˈdɪfrəns/", chinese: "差异；不同", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 260, english: "different", phonetic: "/ˈdɪfrənt/", chinese: "不同的；有差异的", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 261, english: "difficult", phonetic: "/ˈdɪfɪkəlt/", chinese: "困难的；艰难的", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 262, english: "difficulty", phonetic: "/ˈdɪfɪkəlti/", chinese: "困难；难题", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 263, english: "discover", phonetic: "/dɪˈskʌvər/", chinese: "发现；发觉", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 264, english: "discovery", phonetic: "/dɪˈskʌvəri/", chinese: "发现；发觉", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 265, english: "discuss", phonetic: "/dɪˈskʌs/", chinese: "讨论；商量", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 266, english: "discussion", phonetic: "/dɪˈskʌʃn/", chinese: "讨论；商量", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 267, english: "disease", phonetic: "/dɪˈziːz/", chinese: "疾病；病", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 268, english: "distance", phonetic: "/ˈdɪstəns/", chinese: "距离；远方", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 269, english: "divide", phonetic: "/dɪˈvaɪd/", chinese: "分开；分隔", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 270, english: "education", phonetic: "/ˌedʒuˈkeɪʃn/", chinese: "教育；培养", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 271, english: "effect", phonetic: "/ɪˈfekt/", chinese: "影响；效果", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 272, english: "effort", phonetic: "/ˈefərt/", chinese: "努力；尝试", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 273, english: "encourage", phonetic: "/ɪnˈkɜːrɪdʒ/", chinese: "鼓励；激励", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 274, english: "energy", phonetic: "/ˈenərdʒi/", chinese: "精力；能量", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 275, english: "environment", phonetic: "/ɪnˈvaɪrənmənt/", chinese: "环境；背景", unit: 0, category: "高频词", difficulty: "medium"},

    // 最后一批高频词汇
    {id: 276, english: "especially", phonetic: "/ɪˈspeʃəli/", chinese: "尤其；特别", unit: 0, category: "副词", difficulty: "medium"},
    {id: 277, english: "examine", phonetic: "/ɪɡˈzæmɪn/", chinese: "检查；调查", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 278, english: "example", phonetic: "/ɪɡˈzæmpl/", chinese: "例子；榜样", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 279, english: "excellent", phonetic: "/ˈeksələnt/", chinese: "优秀的；杰出的", unit: 0, category: "形容词", difficulty: "medium"},
    {id: 280, english: "excite", phonetic: "/ɪkˈsaɪt/", chinese: "使激动；使兴奋", unit: 0, category: "动词", difficulty: "medium"},
    {id: 281, english: "excuse", phonetic: "/ɪkˈskjuːz/", chinese: "原谅；借口", unit: 0, category: "动词", difficulty: "medium"},
    {id: 282, english: "exercise", phonetic: "/ˈeksərsaɪz/", chinese: "锻炼；练习", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 283, english: "expect", phonetic: "/ɪkˈspekt/", chinese: "期望；预料", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 284, english: "experience", phonetic: "/ɪkˈspɪriəns/", chinese: "经验；经历", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 285, english: "explain", phonetic: "/ɪkˈspleɪn/", chinese: "解释；说明", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 286, english: "express", phonetic: "/ɪkˈspres/", chinese: "表达；表示", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 287, english: "fact", phonetic: "/fækt/", chinese: "事实；真相", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 288, english: "fail", phonetic: "/feɪl/", chinese: "失败；不及格", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 289, english: "famous", phonetic: "/ˈfeɪməs/", chinese: "著名的；出名的", unit: 0, category: "形容词", difficulty: "medium"},
    {id: 290, english: "fantastic", phonetic: "/fænˈtæstɪk/", chinese: "极好的；了不起的", unit: 0, category: "形容词", difficulty: "medium"},

    // 最终批次高频词汇
    {id: 291, english: "prefer", phonetic: "/prɪˈfɜːr/", chinese: "更喜欢；宁愿", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 292, english: "prepare", phonetic: "/prɪˈper/", chinese: "准备；预备", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 293, english: "present", phonetic: "/ˈpreznt/", chinese: "礼物；现在的", unit: 0, category: "多义词", difficulty: "medium"},
    {id: 294, english: "pressure", phonetic: "/ˈpreʃər/", chinese: "压力；压迫", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 295, english: "prevent", phonetic: "/prɪˈvent/", chinese: "阻止；预防", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 296, english: "problem", phonetic: "/ˈprɑːbləm/", chinese: "问题；难题", unit: 0, category: "基础词", difficulty: "easy"},
    {id: 297, english: "produce", phonetic: "/prəˈduːs/", chinese: "生产；引起", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 298, english: "product", phonetic: "/ˈprɑːdʌkt/", chinese: "产品；制品", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 299, english: "program", phonetic: "/ˈproʊɡræm/", chinese: "节目；程序", unit: 0, category: "高频词", difficulty: "medium"},
    {id: 300, english: "progress", phonetic: "/ˈprɑːɡres/", chinese: "进步；进展", unit: 0, category: "高频词", difficulty: "medium"}
];

// 单词分类数据
const categories = {
    unit: {
        0: "综合词汇",
        1: "Unit 1: How can we become good learners?",
        2: "Unit 2: I think that mooncakes are delicious!",
        3: "Unit 3: I'm more outgoing than my sister.",
        4: "Unit 4: What's the best movie theater?",
        5: "Unit 5: What are the shirts made of?",
        6: "Unit 6: When was it invented?",
        7: "Unit 7: Teenagers should be allowed to choose their own clothes.",
        8: "Unit 8: It must belong to Carla.",
        9: "Unit 9: I like music that I can dance to.",
        10: "Unit 10: You're supposed to shake hands.",
        11: "Unit 11: Sad movies make me cry.",
        12: "Unit 12: Life is full of the unexpected.",
        13: "Unit 13: We're trying to save the earth!",
        14: "Unit 14: I remember meeting all of you in Grade 7."
    },
    category: {
        "基础词": "基础常用词汇",
        "高频词": "考试高频词汇",
        "口语词": "口语常用词汇",
        "学科词": "学科专业词汇",
        "节日词": "节日相关词汇",
        "性格词": "性格描述词汇",
        "场所词": "场所地点词汇",
        "材料词": "材料质地词汇",
        "科技词": "科技产品词汇",
        "颜色词": "颜色描述词汇",
        "名词": "常用名词",
        "动词": "常用动词",
        "形容词": "常用形容词",
        "副词": "常用副词",
        "多义词": "多义词"
    },
    difficulty: {
        "easy": "简单",
        "medium": "中等",
        "hard": "困难"
    }
};

// 导出数据
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { wordsData, categories };
}